name: Playground Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/components/playground/**'
      - 'app/components/sandbox/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/components/playground/**'
      - 'app/components/sandbox/**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: playground-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright test